// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BigTime: typeof import('./src/components/bigTime.vue')['default']
    'BigTime copy': typeof import('./src/components/bigTime copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'HelloWorld copy': typeof import('./src/components/HelloWorld copy.vue')['default']
    SmallTime: typeof import('./src/components/smallTime.vue')['default']
    Time: typeof import('./src/components/time.vue')['default']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
    Weather: typeof import('./src/components/weather.vue')['default']
  }
}

export { }
