// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BigTime: typeof import('./src/components/bigTime.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Rss: typeof import('./src/components/rss.vue')['default']
    SmallTime: typeof import('./src/components/smallTime.vue')['default']
    TodoList: typeof import('./src/components/todoList.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
    Weather: typeof import('./src/components/weather.vue')['default']
  }
}

export { }
